Repository YifanYes/the-fishery, pull requests merged in 2024-05, with the labels that each got.

#2 feat: Auth
  app/controllers/auth/login_controller.ts
  app/controllers/auth/register_user_controller.ts
  app/models/user.ts
  app/validators/auth/login_validator.ts
  app/validators/auth/register_user_validator.ts
  app/validators/rules/unique.ts
  config/shield.ts
  database/migrations/1716742967426_create_users_table.ts
  inertia/pages/home.tsx
  start/routes.ts
Labels: enhancement

#1 chore: Add main code formatting configuration
  .eslintrc.js
  .prettierrc
  package-lock.json
  package.json
Labels: chore

#3 feat: Logout
  app/controllers/auth/logout_controller.ts
  start/routes.ts
Labels: enhancement

#4 feat: Added theme context and basic config to app
  inertia/app/app.tsx
  inertia/app/ssr.tsx
  inertia/context/ThemeContext.tsx
  inertia/styles/default.ts
  inertia/types/style.types.ts
  inertia/utils/Color.helper.ts
  inertia/utils/Theme.helper.ts
  inertia/utils/index.ts
  vite.config.ts
Labels: feature

#6 feat: Added basic texts components
  inertia/components/atoms/texts/BaseText.tsx
  inertia/components/atoms/texts/Em.tsx
  inertia/components/atoms/texts/Heading.tsx
  inertia/components/atoms/texts/Link.tsx
  inertia/components/atoms/texts/List.tsx
  inertia/components/atoms/texts/Strong.tsx
  inertia/components/atoms/texts/Text.tsx
  inertia/components/atoms/texts/index.ts
Labels: feature

#7 feat: Add missing branch content
  inertia/components/atoms/layout/Box.tsx
  inertia/components/atoms/layout/Container.tsx
  inertia/components/atoms/layout/Flex.tsx
  inertia/components/atoms/layout/Grid.tsx
  inertia/components/atoms/layout/Page.tsx
  inertia/components/atoms/layout/Section.tsx
  inertia/components/atoms/layout/index.ts
  inertia/components/atoms/texts/BaseText.tsx
  inertia/components/atoms/texts/Em.tsx
  inertia/components/atoms/texts/Heading.tsx
  inertia/components/atoms/texts/Link.tsx
  inertia/components/atoms/texts/List.tsx
  inertia/components/atoms/texts/Strong.tsx
  inertia/components/atoms/texts/Text.tsx
  inertia/components/atoms/texts/index.ts
  package-lock.json
  package.json
Labels: feature

#8 feat: Templates
  app/controllers/auth/login.controller.ts
  app/controllers/auth/logout.controller.ts
  app/controllers/auth/logout_controller.ts
  app/controllers/auth/register_user.controller.ts
  app/controllers/templates/create_template.controller.ts
  app/controllers/templates/delete_template.controller.ts
  app/controllers/templates/get_template.controller.ts
  app/controllers/templates/get_templates_list.controller.ts
  app/controllers/templates/update_template.controller.ts
  app/helpers/transformer.helper.ts
  app/middleware/auth.middleware.ts
  app/middleware/container_bindings.middleware.ts
  app/models/template.ts
  app/models/user.ts
  app/services/template.service.ts
  app/transformers/auth/user.transformer.ts
  app/transformers/templates/template.transformer.ts
  app/types/auth.types.ts
  app/types/template.types.ts
  app/validators/auth/login.validator.ts
  app/validators/auth/register_user.validator.ts
  app/validators/templates/create_template.validator.ts
  app/validators/templates/update_template.validator.ts
  database/migrations/1716983657897_create_templates_table.ts
  package.json
  start/kernel.ts
  start/routes.ts
  start/routes/private/templates.routes.ts
Labels: enhancement

#10 feat: Form basic components
  inertia/components/atoms/buttons/Button.tsx
  inertia/components/atoms/buttons/index.ts
  inertia/components/atoms/errors/InputError.tsx
  inertia/components/atoms/errors/index.ts
  inertia/components/atoms/index.ts
  inertia/components/atoms/inputs/FormInput.tsx
  inertia/components/atoms/inputs/Input.tsx
  inertia/components/atoms/inputs/index.ts
  inertia/components/atoms/inputs/variants/TextInput.tsx
  inertia/components/atoms/inputs/variants/index.ts
  inertia/components/atoms/loaders/ButtonLoader.tsx
  inertia/components/atoms/loaders/Loader.tsx
  inertia/components/atoms/loaders/index.ts
  inertia/components/atoms/texts/Label.tsx
  inertia/components/atoms/texts/index.ts
  inertia/components/atoms/toasts/Toast.tsx
  inertia/components/atoms/toasts/index.ts
  package-lock.json
  package.json
Labels: feature
